controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: ''
    controller: 'App\Controller\AccueilController::index'

cabinet_inscription:
    path: 'inscription'
    controller: 'App\Controller\CabinetInscriptionController::index'

admin_inscriptions:
    path: 'demande-inscription'
    controller: 'App\Controller\AdminInscriptionController::index'

valider_inscription:
    path: 'admin/valider_inscription/{id}'
    controller: 'App\Controller\AdminInscriptionController::validerInscription'

refuser_inscription:
    path: 'admin/refuser_inscription/{id}'
    controller: 'App\Controller\AdminInscriptionController::refuserInscription'

app_login:
    path: 'connexion'
    controller: App\Controller\SecurityController::index

appp_loginn:
    path: 'connection'
    controller: App\Controller\SecurityController::login

route_paiement:
    path: /paiement
    controller: App\Controller\PaiementController::index

route_success:
    path: /paiement/succes
    controller: App\Controller\PaiementController::index

route_cancel:
    path: /paiement/annulation
    controller: App\Controller\PaiementController::index
